version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - network-cloud
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - 3001:3001
    networks: 
     - network-cloud
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks: 
     - network-cloud

networks:
  network-cloud:

volumes: 
  mongodb_data:
